<tr><td><div id="tweet_736308087573864448" class="tweet_odd">Oh shucks! https://t.co/vEOSMjrWoq<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/736308087573864448">5 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_736307680260788224" class="tweet_even"><a class="$class" href="http://twitter.com/MarcyLane">@MarcyLane</a> We're sorry you had a bad experience. We'd love a chance to make it up to you. Keep an eye on your email, we'll be reaching out.<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/736307680260788224">5 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_735333746304516096" class="tweet_odd">RT <a class="$class" href="http://twitter.com/timeoutla">@timeoutla</a>: The winners of the 2016 Time Out Los Angeles Bar Awards https://t.co/MQUvD0BGpp <a class="$class" href="http://twitter.com/#!/search?q=%23timeoutbarawards">#timeoutbarawards</a> https://t.co/4lUcyYAJEx<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/735333746304516096">8 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_734988671108055041" class="tweet_even">We're over the moon. Honored to have won <a class="$class" href="http://twitter.com/timeoutla">@timeoutla</a> <a class="$class" href="http://twitter.com/#!/search?q=%23BarOfTheYear">#BarOfTheYear</a> award 🙌 https://t.co/Kak8pMDQ43<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/734988671108055041">9 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_734878474314252289" class="tweet_odd">We're all a blush. Honored to be a finalist of Time Out LA's 2016 Bar Awards | https://t.co/B1dQ2sKvDE<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/734878474314252289">9 days ago.</a> from <a href="http://twitter.com" rel="nofollow">Twitter Web Client</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_733911000567554048" class="tweet_even">Lucky smoke for the win. Hiya Hollywood. https://t.co/btLMoVIkmi<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/733911000567554048">12 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_733764942692683776" class="tweet_odd">RT <a class="$class" href="http://twitter.com/citizine">@citizine</a>: There's not enough time in life to drink crappy cocktails. <a class="$class" href="http://twitter.com/SpareRoomHwood">@SpareRoomHwood</a> <a class="$class" href="http://twitter.com/hwood_roosevelt">@hwood_roosevelt</a> https://t.co/mxHR8EGFed https://t…<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/733764942692683776">12 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_733684051509272576" class="tweet_even">RT <a class="$class" href="http://twitter.com/EatWinsome">@EatWinsome</a>: Good news, we're HIRING all positions. Love being nice to people? Get your kicks from being a… https://t.co/EzR5mAWIpj<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/733684051509272576">13 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_730077928285863939" class="tweet_odd">Tropical everything. Join us for an Evening of <a class="$class" href="http://twitter.com/#!/search?q=%23tiki">#tiki</a> with <a class="$class" href="http://twitter.com/PlantationRums">@PlantationRums</a> - Tomorrow night https://t.co/AP9ua4TZYE<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/730077928285863939">22 days ago.</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_726232614248423424" class="tweet_even">RT <a class="$class" href="http://twitter.com/hungryxpat">@hungryxpat</a>: Want to know what bartenders order when they go out? Check it: https://t.co/QekCdd6sbC <a class="$class" href="http://twitter.com/carisunnie">@carisunnie</a> <a class="$class" href="http://twitter.com/SpareRoomHwood">@SpareRoomHwood</a> https://…<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/726232614248423424">April 29, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_726157067904495616" class="tweet_odd">Let's play. See you tonight Los Angeles. @ The Spare Room https://t.co/u05yEqRQtb<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/726157067904495616">April 29, 2016</a> from <a href="http://instagram.com" rel="nofollow">Instagram</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_726155403298377729" class="tweet_even">Everydays are for whiskey sippin' 😉 https://t.co/XdDiLE10lV<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/726155403298377729">April 29, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_725357137602482176" class="tweet_odd">Tonight! Join us for <a class="$class" href="http://twitter.com/themattson2">@themattson2</a> final <a class="$class" href="http://twitter.com/#!/search?q=%23jazzilla">#jazzilla</a> feat Carlos Niño's of <a class="$class" href="http://twitter.com/dublab">@dublab</a> and Jordon… https://t.co/bVS8IQcRqv<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/725357137602482176">April 27, 2016</a> from <a href="http://instagram.com" rel="nofollow">Instagram</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_720098624462524416" class="tweet_even">Tuesday, commonly referred to as "stay home and work on your bowling stance night." We're closed… https://t.co/j6f2IEd8c5<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/720098624462524416">April 12, 2016</a> from <a href="http://instagram.com" rel="nofollow">Instagram</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_718620185544904704" class="tweet_odd">🙏 https://t.co/uchSB39m1L<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/718620185544904704">April 08, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_718619960705097729" class="tweet_even">It's Friday night, what else could you possibly want? Oh yeah, cocktails and bowling. And cocktail dresses. And bowling. See you tonight.<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/718619960705097729">April 08, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_718619542100905985" class="tweet_odd">RT <a class="$class" href="http://twitter.com/TimeOutNewYork">@TimeOutNewYork</a>: 18 top bartenders share their favorite cocktails (via <a class="$class" href="http://twitter.com/TimeOutUS">@TimeOutUS</a>): https://t.co/k0G57LG121 https://t.co/romCcLj2qw<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/718619542100905985">April 08, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_717177827259342848" class="tweet_even">Monday also means Midori Shower • Hendrick's gin, Midori, Kaffir Lime, Egg White, Matcha Green Tea - See you tonight <a class="$class" href="http://twitter.com/DrinkMidori">@DrinkMidori</a><br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/717177827259342848">April 04, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_717177491203293184" class="tweet_odd">Monday night means <a class="$class" href="http://twitter.com/#!/search?q=%23thespareroom">#thespareroom</a> Bowling Club is ON. With <a class="$class" href="http://twitter.com/TheUniqueSpace">@TheUniqueSpace</a> <a class="$class" href="http://twitter.com/Supreme_NYC">@Supreme_NYC</a>  <a class="$class" href="http://twitter.com/sundancelabs">@sundancelabs</a> and others https://t.co/5h6tIlQAHo<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/717177491203293184">April 04, 2016</a> from <a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td><div id="tweet_709646647094091776" class="tweet_even">Congrats (or not) to Team shinola for "winning" the <a class="$class" href="http://twitter.com/#!/search?q=%23SpareRoomBowlingLeague">#SpareRoomBowlingLeague</a> Loser Bowl and… https://t.co/8cpet7W2DS<br /><span class="tweet_source">Posted <a href="http://twitter.com/#!/SpareRoomHwood/status/709646647094091776">March 15, 2016</a> from <a href="http://instagram.com" rel="nofollow">Instagram</a></span><div class="tweet_clear">&nbsp;</div></div>

</td></tr><tr><td class="twitter_date"><small>Last updated Jun 02 @ 9:46 am pst</small></tr></td>